# This file was generated by GoReleaser. DO NOT EDIT.
cask "smuggle" do
  app "Smuggle.app"

  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "54f3cba6d95b0d0095973251f874536b192e7a143f22d51556cc7d4f08158874"
      url "https://github.com/smuggle-dev/smuggle/releases/download/v#{version}/smuggle_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "aff50a223d97384485fd092aa3651e39c40c3dc7f045731faaf8c960ebcf9b09"
      url "https://github.com/smuggle-dev/smuggle/releases/download/v#{version}/smuggle_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "smuggle"
  desc "Dropbox for devs — continuous, end-to-end-encrypted folder sync"
  homepage "https://github.com/smuggle-dev/smuggle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "smuggle"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/smuggle"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/Smuggle.app"]
    end
  end

  # No zap stanza required

end
