# This file was generated by GoReleaser. DO NOT EDIT.
cask "smuggle" do
  version "0.2.5"

  on_macos do
    on_intel do
      sha256 "e7ad74be2cdb1223a5e09f5cc07d38a19ad830db43090c829b4b1716a3b0151e"
      url "https://github.com/smuggle-dev/smuggle/releases/download/v#{version}/smuggle_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "62df648838337be9b3c34179087c0b0581c77ff9daf0431ae98bb60ab6b1cac4"
      url "https://github.com/smuggle-dev/smuggle/releases/download/v#{version}/smuggle_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "68d5c31f9c665bbe546099b5b508de2069bb8f671a7fb8680262b3ca8bdc3078"
      url "https://github.com/smuggle-dev/smuggle/releases/download/v#{version}/smuggle_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8e112a81b5a0524c43786e17d179a66b47e1066f08551b1156b4df7a58ec446e"
      url "https://github.com/smuggle-dev/smuggle/releases/download/v#{version}/smuggle_#{version}_linux_arm64.tar.gz"
    end
  end

  name "smuggle"
  desc "Dropbox for devs — continuous, end-to-end-encrypted folder sync"
  homepage "https://github.com/smuggle-dev/smuggle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "smuggle"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/smuggle"]
    end
  end

  # No zap stanza required

end
