# This file was generated by GoReleaser. DO NOT EDIT.
cask "smuggle" do
  app "Smuggle.app"

  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "4a5c6aab224767a493d71aa6db60b1a550bc17ced0e4396379db2b68f044f810"
      url "https://github.com/smuggle-dev/smuggle/releases/download/v#{version}/smuggle_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a7b172f906299256e7d77ea51c1a0970a7390c7f4428775878dee6f2ab0f5d1f"
      url "https://github.com/smuggle-dev/smuggle/releases/download/v#{version}/smuggle_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "smuggle"
  desc "Dropbox for devs — continuous, end-to-end-encrypted folder sync"
  homepage "https://github.com/smuggle-dev/smuggle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "smuggle"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/smuggle"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/Smuggle.app"]
    end
  end

  # No zap stanza required

end
